sudo chmod +x cleaningScript.sh
sudo chmod +x createFolders.sh
sudo chmod +x run2NodeConfigServer.sh
sudo chmod +x run2NodeShard1.sh
sudo chmod +x run2NodeShard2.sh
sudo chmod +x run2NodeShard3.sh
sudo chmod +x runMongosWith2ConfigServer.sh
sudo chmod +x runConfigServer.sh
sudo chmod +x runShard.sh
sudo chmod +x runShardConf.sh
sudo chmod +x setEnv.sh
